ae_project:
  outputs:
    dev:
      dataset: dbt_berti
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: analytics-394014
      threads: 1
      type: bigquery
  target: dev
